 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

 import Data.DongPhuc_DA;
 import Data.UserSession;
 import Exception.NullValueException;
 import Model.DialogHelper;
 import Model.DongPhuc;

 import javax.swing.*;
 import javax.swing.table.DefaultTableModel;
 import java.util.ArrayList;

/**
 *
 * @author pc
 */
public class QuanLyKho extends javax.swing.JFrame {
    DongPhuc_DA dp = new DongPhuc_DA();
    DefaultTableModel model;
    /**
     * Creates new form QuanLyKho
     */
    public QuanLyKho() {
        this.setTitle("Quản lý kho");
        initComponents();
        initSize();
        model = (DefaultTableModel) tblTable.getModel();
        tblTable.setModel(model);
        setLocationRelativeTo(null);
        show_result();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxsize = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jtxdg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxmsp = new javax.swing.JTextField();
        jtxsl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jrbtmale = new javax.swing.JRadioButton();
        jrbtfemale = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnthem = new javax.swing.JButton();
        btncapnhat = new javax.swing.JButton();
        btnsapxep = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jbtback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(762, 542));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ KHO");

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên", "Kích cỡ", "Loại", "Số lượng", "Đơn giá"
            }
        ));
        tblTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTable);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Tên sản phẩm");

        jtxten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtenActionPerformed(evt);
            }
        });

        jLabel3.setText("Kích cỡ");

        cbxsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxsizeActionPerformed(evt);
            }
        });

        jLabel7.setText("Đơn giá");

        jLabel5.setText("Mã sản phẩm");

        jtxmsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxmspActionPerformed(evt);
            }
        });

        jtxsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxslActionPerformed(evt);
            }
        });

        jLabel4.setText("Số lượng");

        jLabel8.setText("Loại");

        buttonGroup2.add(jrbtmale);
        jrbtmale.setText("Nam");
        jrbtmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtmaleActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrbtfemale);
        jrbtfemale.setText("Nữ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Thông tin sản phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(cbxsize, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(245, 245, 245))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jtxten, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel4))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxdg, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(238, 238, 238)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbtmale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jrbtfemale))
                            .addComponent(jtxmsp)
                            .addComponent(jtxsl))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtxmsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jtxdg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jrbtmale)
                        .addComponent(jrbtfemale)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btncapnhat.setText("Cập nhật");
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });

        btnsapxep.setText("Sắp xếp");
        btnsapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsapxepActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Chức năng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnthem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncapnhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsapxep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnthem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncapnhat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsapxep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnxoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtback.setText("Quay Lại");
        jbtback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbtback, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtback, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initSize(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("XS");
        model.addElement("S");
        model.addElement("M");
        model.addElement("L");
        model.addElement("XL");
        model.addElement("XXL");
        cbxsize.setModel(model);
    }
    
    private void jtxtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtenActionPerformed

    private void jtxslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxslActionPerformed

    private void cbxsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxsizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxsizeActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        try{
            DongPhuc temp = new DongPhuc();
            check_null(jtxmsp.getText());
            check_null(jtxten.getText());
            check_null(jtxdg.getText());
            check_null(jtxsl.getText());
            check_jrbutton(buttonGroup2.getSelection());
            temp.setMasp(jtxmsp.getText());
            temp.setTen(jtxten.getText());
            
            int gia = Integer.valueOf(jtxdg.getText());
            temp.setGia(gia);
            int soluong = Integer.valueOf(jtxsl.getText());
            temp.setSoluong(soluong);
            temp.setKichco(cbxsize.getSelectedItem().toString());
            if(jrbtmale.isSelected())   temp.setLoai("Nam");
            if(jrbtfemale.isSelected())    temp.setLoai("Nữ");
            dp.add_dp(temp);
            show_result_add();
            new DialogHelper().infoDialogMess("Thêm thông tin sản phẩm thành công");
            reset_text();
        }catch(Exception e){
            e.getStackTrace();
            new DialogHelper().infoDialogMess("Thao tác không thành công", "Lỗi");
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsapxepActionPerformed
        // TODO add your handling code here:
        dp.sort_dp();
        model.setRowCount(0);
        show_result();
        new DialogHelper().infoDialogMess("Sắp xếp thông tin sản phẩm thành công");
    }//GEN-LAST:event_btnsapxepActionPerformed

    private void jtxmspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxmspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxmspActionPerformed

    private void jrbtmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtmaleActionPerformed

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatActionPerformed
        // TODO add your handling code here:
        try{
            int row = tblTable.getSelectedRow();
            
            DongPhuc temp = new DongPhuc();
            check_null(jtxmsp.getText());
            check_null(jtxten.getText());
            check_null(jtxdg.getText());
            check_null(jtxsl.getText());
            check_jrbutton(buttonGroup2.getSelection());
            temp.setMasp(jtxmsp.getText());
            temp.setTen(jtxten.getText());

            int gia = Integer.valueOf(jtxdg.getText());
            temp.setGia(gia);
            int soluong = Integer.valueOf(jtxsl.getText());
            temp.setSoluong(soluong);
            temp.setKichco(cbxsize.getSelectedItem().toString());
            if(jrbtmale.isSelected())   temp.setLoai("Nam");
            if(jrbtfemale.isSelected())    temp.setLoai("Nữ");
            
            tblTable.setValueAt(temp.getTen(), row, 1);
            tblTable.setValueAt(temp.getMasp(), row, 0);
            tblTable.setValueAt(temp.getQual(), row, 4);
            tblTable.setValueAt(temp.getGia(), row, 5);
            tblTable.setValueAt(temp.getKichco(), row, 2);
            tblTable.setValueAt(temp.getLoai(), row, 3);
            
            model.fireTableDataChanged();
            new DialogHelper().infoDialogMess("Cập nhật thông tin sản phẩm thành công");
            reset_text();
        }catch(Exception e){
            e.getStackTrace();
            new DialogHelper().infoDialogMess("Lỗi thao tác", "Lỗi");
        } 
    }//GEN-LAST:event_btncapnhatActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        try{
            DongPhuc temp = new DongPhuc();
            check_null(jtxmsp.getText());
            check_null(jtxten.getText());
            check_null(jtxdg.getText());
            check_null(jtxsl.getText());
            check_jrbutton(buttonGroup2.getSelection());
            temp.setMasp(jtxmsp.getText());
            temp.setTen(jtxten.getText());

            int gia = Integer.valueOf(jtxdg.getText());
            temp.setGia(gia);
            int soluong = Integer.valueOf(jtxsl.getText());
            temp.setSoluong(soluong);
            temp.setKichco(cbxsize.getSelectedItem().toString());
            if(jrbtmale.isSelected())   temp.setLoai("Nam");
            if(jrbtfemale.isSelected())    temp.setLoai("Nữ");
            int index = findRowIndex(temp);
            dp.remove_dp(index);
            if (index != -1) {
                model.removeRow(index);
                model.fireTableDataChanged();
            }
            model.fireTableDataChanged();
            new DialogHelper().infoDialogMess("Xóa thông tin sản phẩm thành công");
            reset_text();
        }catch(Exception e){
            e.getStackTrace();
            new DialogHelper().infoDialogMess("Lỗi thao tác", "Lỗi");
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void tblTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) { // Kiểm tra sự kiện đúp chuột
            int row = tblTable.getSelectedRow(); // Lấy chỉ mục hàng của dòng được chọn
            if (row != -1) { // Kiểm tra xem có dòng nào được chọn hay không
                // Lấy dữ liệu từ mỗi cột của dòng
                String masp = tblTable.getValueAt(row, 0).toString();
                String tensp = tblTable.getValueAt(row, 1).toString();
                String kichco = tblTable.getValueAt(row, 2).toString();
                String loai = tblTable.getValueAt(row, 3).toString();
                String soluong = tblTable.getValueAt(row, 4).toString();
                String dongia = tblTable.getValueAt(row, 5).toString();
                
                jtxten.setText(tensp);
                jtxmsp.setText(masp);
                jtxsl.setText(soluong);
                jtxdg.setText(dongia);
                if(loai.equals("Nam"))   jrbtmale.setSelected(true);
                else    jrbtfemale.setSelected(true);
                cbxsize.setSelectedItem(kichco);
            }
        }
    }//GEN-LAST:event_tblTableMouseClicked

    private void jbtbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtbackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        int role = UserSession.getUserRole();
        //System.out.println(role + " Dặt hàng");
        if(role == 2)
            new Trang_chu_QTV().setVisible(true);
        else  new Trang_chu_NV().setVisible(true);
    }//GEN-LAST:event_jbtbackActionPerformed
    public void reset_text(){
        jtxten.setText("");
        jtxmsp.setText("");
        jtxdg.setText("");
        jtxsl.setText("");
        buttonGroup2.clearSelection();   
    }
    public void show_result_add(){
        ArrayList<DongPhuc> temp = dp.getDp();
        DongPhuc i = temp.get(temp.size() - 1);
        model.addRow(new Object[]{
                i.getMasp(),
                i.getTen(),
                i.getKichco(),
                i.getLoai(),
                i.getQual(),
                i.getGia()
            });
    }
    public void show_result(){
        for(DongPhuc i : dp.getDp()){
            model.addRow(new Object[]{
                i.getMasp(),
                i.getTen(),
                i.getKichco(),
                i.getLoai(),
                i.getQual(),
                i.getGia()
            });
        }
    }
    
    public void check_null(String temp) throws NullValueException{
        if(temp.equals("")){
            throw new NullValueException("Lỗi giá trị NULL");
        }
    }
    public void check_jrbutton(ButtonModel temp) throws NullValueException{
        if(temp.equals("")){
            throw new NullValueException("Lỗi giá trị NULL");
        }
    }
    
    public  int findRowIndex(DongPhuc dongphuc) {
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(dongphuc.getMasp())
                && model.getValueAt(i, 1).equals(dongphuc.getTen())
                && model.getValueAt(i, 2).equals(dongphuc.getKichco())
                && model.getValueAt(i, 4).equals(dongphuc.getQual())
                && model.getValueAt(i, 5).equals(dongphuc.getGia())
                && model.getValueAt(i, 3).equals(dongphuc.getLoai())) {
                return i;
            }
        }
        return -1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncapnhat;
    private javax.swing.JButton btnsapxep;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbxsize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton jbtback;
    private javax.swing.JRadioButton jrbtfemale;
    private javax.swing.JRadioButton jrbtmale;
    private javax.swing.JTextField jtxdg;
    private javax.swing.JTextField jtxmsp;
    private javax.swing.JTextField jtxsl;
    private javax.swing.JTextField jtxten;
    private javax.swing.JTable tblTable;
    // End of variables declaration//GEN-END:variables
}
