/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Data.TaiKhoan_DA;
import Exception.NullValueException;
import Model.DialogHelper;
import Model.User;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author pc
 */
public class QuanLyTaiKhoan extends javax.swing.JFrame {
    TaiKhoan_DA taikhoan = new TaiKhoan_DA();
    DefaultTableModel model;
    /**
     * Creates new form QuanLyBaoCao
     */
    public QuanLyTaiKhoan() {
        this.setTitle("Quản lý tài khoản");
        this.setLocationRelativeTo(null);
        initComponents();
        model = (DefaultTableModel) jTabletk.getModel();
        jTabletk.setModel(model);
        show_result();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxmnv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxmk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jrbtnv = new javax.swing.JRadioButton();
        jrbtqtv = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jrbthd = new javax.swing.JRadioButton();
        jrbtbk = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabletk = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ TÀI KHOẢN");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Họ và tên");

        jLabel3.setText("Mã nhân viên");

        jtxmnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxmnvActionPerformed(evt);
            }
        });

        jLabel4.setText("Tài khoản");

        jLabel5.setText("Mật khẩu");

        jtxmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxmkActionPerformed(evt);
            }
        });

        jLabel7.setText("Vai trò");

        buttonGroup1.add(jrbtnv);
        jrbtnv.setText("Nhân viên");
        jrbtnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnvActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtqtv);
        jrbtqtv.setText("Quản trị viên");

        jLabel8.setText("Trạng thái");

        buttonGroup2.add(jrbthd);
        jrbthd.setText("Hoạt động");

        buttonGroup2.add(jrbtbk);
        jrbtbk.setText("Bị khóa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbtnv, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbtqtv, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtxtk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addComponent(jtxten, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxmk)
                    .addComponent(jtxmnv)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbtbk, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbthd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtxmnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jtxtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jrbtnv)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jrbthd)
                                    .addComponent(jLabel8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbtbk)
                            .addComponent(jrbtqtv)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Tạo tài khoản");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cập nhật");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Tìm kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Quay lại");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabletk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ và tên", "Tài khoản", "Mật khẩu", "Vai trò", "Trạng thái"
            }
        ));
        jTabletk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabletkMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTabletk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxmnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxmnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxmnvActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String ten = jtxten.getText();
            String ma = jtxmnv.getText();
            String tk = jtxtk.getText();
            String mk = jtxmk.getText();
            check(ten);
            check(ma);
            check(tk);
            check(mk);
            System.out.println("haha");
            String chucvu = "";
            if(jrbtqtv.isSelected())    chucvu = "Quản trị viên";
            if(jrbtnv.isSelected())     chucvu = "Nhân viên";
            String trangthai = "";
            if(jrbthd.isSelected())     trangthai = "Hoạt động";
            if(jrbtbk.isSelected())     trangthai = "Bị khóa";
            check_b(buttonGroup1.getSelection());
            check_b(buttonGroup2.getSelection());
            System.out.println("hihi");
            User ac = new User(ten,ma, chucvu, trangthai,tk,mk);
            taikhoan.addTk(ac);
            new DialogHelper().infoDialogMess("Thêm tài khoản thành công");
            show_result_add();
            reset_text();
        }catch(Exception e){
            e.getStackTrace();
            new DialogHelper().infoDialogMess("Thao tác không thành công", "Lỗi");
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxmkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxmkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String ten = jtxten.getText();
            String ma = jtxmnv.getText();
            String tk = jtxtk.getText();
            String mk = jtxmk.getText();
            check(ten);
            check(ma);
            check(tk);
            check(mk);
            String chucvu = "";
            if(jrbtqtv.isSelected())    chucvu = "Quản trị viên";
            if(jrbtnv.isSelected())     chucvu = "Nhân viên";
            String trangthai = "";
            if(jrbthd.isSelected())     trangthai = "Hoạt động";
            if(jrbtbk.isSelected())     trangthai = "Bị khóa";
            check_b(buttonGroup1.getSelection());
            check_b(buttonGroup2.getSelection());
            User ac = new User(ten,ma, chucvu, trangthai,tk,mk);
            int rowIndex = findRowIndex(ac);
            taikhoan.deleteTK(rowIndex);
            if (rowIndex != -1) {
                model.removeRow(rowIndex);
                model.fireTableDataChanged();
            }
            new DialogHelper().infoDialogMess("Xóa tài khoản thành công");
            update();
            reset_text();
        }catch(Exception e){
            e.getStackTrace();
            new DialogHelper().infoDialogMess("Thao tác không thành công", "Lỗi");
        }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTabletkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabletkMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) { // Kiểm tra sự kiện đúp chuột
            int row = jTabletk.getSelectedRow(); // Lấy chỉ mục hàng của dòng được chọn
            if (row != -1) { // Kiểm tra xem có dòng nào được chọn hay không
                // Lấy dữ liệu từ mỗi cột của dòng
                String maNV = jTabletk.getValueAt(row, 0).toString();
                String tenNV = jTabletk.getValueAt(row, 1).toString();
                String taiKhoan = jTabletk.getValueAt(row, 2).toString();
                String matKhau = jTabletk.getValueAt(row, 3).toString();
                String chucVu = jTabletk.getValueAt(row, 4).toString();
                String trangThai = jTabletk.getValueAt(row, 5).toString();
                
                jtxten.setText(tenNV);
                jtxmnv.setText(maNV);
                jtxtk.setText(taiKhoan);
                jtxmk.setText(matKhau);
                if(chucVu == "Nhân Viên")   jrbtnv.setSelected(true);
                else    jrbtqtv.setSelected(true);
                if(trangThai == "Hoạt động")    jrbthd.setSelected(true);
                else    jrbtbk.setSelected(true);
            }
        }
    }//GEN-LAST:event_jTabletkMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            int row = jTabletk.getSelectedRow();
            
            String ten = jtxten.getText();
            String ma = jtxmnv.getText();
            String tk = jtxtk.getText();
            String mk = jtxmk.getText();
            check(ten);
            check(ma);
            check(tk);
            check(mk);
            String chucvu = "";
            if(jrbtqtv.isSelected())    chucvu = "Quản trị viên";
            if(jrbtnv.isSelected())     chucvu = "Nhân viên";
            String trangthai = "";
            if(jrbthd.isSelected())     trangthai = "Hoạt động";
            if(jrbtbk.isSelected())     trangthai = "Bị khóa";
            check_b(buttonGroup1.getSelection());
            check_b(buttonGroup2.getSelection());
            
            jTabletk.setValueAt(ten, row, 1);
            jTabletk.setValueAt(ma, row, 0);
            jTabletk.setValueAt(chucvu, row, 4);
            jTabletk.setValueAt(trangthai, row, 5);
            jTabletk.setValueAt(tk, row, 2);
            jTabletk.setValueAt(mk, row, 3);

            new DialogHelper().infoDialogMess("Cập nhật tài khoản thành công");
            update();
            reset_text();
        }catch(Exception e){
            e.getStackTrace();
            new DialogHelper().infoDialogMess("Thao tác không thành công", "Lỗi");
        }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String mnv = jtxmnv.getText();
        for(User i : taikhoan.getQl()){
            if(i.getManv().equals(mnv)){
                jtxten.setText(i.getHovaten());
                jtxmnv.setText(mnv);
                jtxtk.setText(i.getTaikhoan());
                jtxmk.setText(i.getMatkhau());
                if(i.getChucvu().equals("Nhân Viên")) {
                    jrbtnv.setSelected(true);
                    jrbtqtv.setSelected(false);
                } 
                else {
                    jrbtnv.setSelected(false);
                    jrbtqtv.setSelected(true);
                }
                if(i.getTrangthai().equals("Hoạt động")) {
                    jrbthd.setSelected(true);
                    jrbtbk.setSelected(false);
                } 
                else {
                    jrbthd.setSelected(false);
                    jrbtbk.setSelected(true);
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        new Trang_chu_QTV().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jrbtnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtnvActionPerformed
    
    public void check(String temp) throws NullValueException{
        if(temp == null)
            throw new NullValueException("Lỗi giá trị null");
    }
    
    public void check_b(ButtonModel check) throws NullValueException{
        if(check == null)
            throw new NullValueException("Lỗi giá trị null");
    }
    public void update(){
        model.fireTableDataChanged();
    }
  
    public  int findRowIndex(User user) {
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(user.getManv())) {
                return i;
            }
        }
        return -1;
    }
    
    public void insert_row(int location, User i){
        model.insertRow(location, new Object[]{
            i.getManv(),
            i.getHovaten(),
            i.getTaikhoan(),
            i.getMatkhau(),
            i.getChucvu(),
            i.getTrangthai()
        });
    }
    
    public void show_result_add(){
        ArrayList<User> temp = taikhoan.getQl();
        User i = temp.get(temp.size() - 1);
        model.addRow(new Object[]{
            i.getManv(),
            i.getHovaten(),
            i.getTaikhoan(),
            i.getMatkhau(),
            i.getChucvu(),
            i.getTrangthai()
        });
    }
    public void show_result(){
        for(User i : taikhoan.getQl()){
            model.addRow(new Object[]{
                i.getManv(),
                i.getHovaten(),
                i.getTaikhoan(),
                i.getMatkhau(),
                i.getChucvu(),
                i.getTrangthai()
            });
        }
    }
    
    public void reset_text(){
        jtxten.setText("");
        jtxmnv.setText("");
        jtxtk.setText("");
        jtxmk.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTabletk;
    private javax.swing.JRadioButton jrbtbk;
    private javax.swing.JRadioButton jrbthd;
    private javax.swing.JRadioButton jrbtnv;
    private javax.swing.JRadioButton jrbtqtv;
    private javax.swing.JTextField jtxmk;
    private javax.swing.JTextField jtxmnv;
    private javax.swing.JTextField jtxten;
    private javax.swing.JTextField jtxtk;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables
}
